apiVersion: v1
kind: Service
metadata:
  labels:
    name: dashboard
  name: dashboard-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  type: LoadBalancer
  selector:
    app: povs
    component: dashboard