kind: ReplicationController
apiVersion: v1beta3
metadata:
  labels:
    app: povs
    name: elasticsearch
    role: data
  name: elasticsearch-data
spec:
  replicas: 1
  selector:
    name: elasticsearch
    role: data
  template:
    metadata:
      labels:
        name: elasticsearch
        role: data
    spec:
        volumes:
          - name: data
            emptyDir: {}
        containers:
          - name: elasticsearch-data
            image: alexlovelltroy/elasticsearch-data
            ports:
              - name: transport
                containerPort: 9300
            volumeMounts:
              - name: data
                mountPath: /data
