kind: ReplicationController
apiVersion: v1beta3
metadata:
  labels:
    app: povs
    name: elasticsearch
    role: master
  name: elasticsearch-master
spec:
  replicas: 1
  selector:
    name: elasticsearch
    role: master
  template:
    metadata:
      labels:
        name: elasticsearch
        role: master
    spec:
        volumes:
          - name: data
            emptyDir: {}
        containers:
          - name: elasticsearch-master
            image: alexlovelltroy/elasticsearch-master
            ports:
              - name: transport
                containerPort: 9300
            volumeMounts:
              - name: data
                mountPath: /data
