kind: ReplicationController
apiVersion: v1beta3
metadata:
  labels:
    app: povs
    name: elasticsearch
    role: client
  name: elasticsearch-client
spec:
  replicas: 1
  selector:
    app: povs
    name: elasticsearch
    role: client
  template:
    metadata:
      labels:
        app: povs
        name: elasticsearch
        role: client
    spec:
        containers:
          - name: elasticsearch-client
            image: alexlovelltroy/elasticsearch-client
            ports:
              - name: http
                containerPort: 9200
              - name: transport
                containerPort: 9300