apiVersion: v1
kind: Service
metadata:
  labels:
    name: elasticsearch
  name: elasticsearch-service
spec:
  ports:
  - port: 9200
    protocol: TCP
    targetPort: 9200
  selector:
    app: povs
    component: elasticsearch