apiVersion: v1beta3
kind: Service
metadata:
  labels:
    name: elasticsearch
  name: elasticsearch-service
spec:
  ports:
  - port: 9200
    protocol: TCP
    targetPort: 9200
  selector:
    app: povs
    name: elasticsearch
    role: server
  type: LoadBalancer
