apiVersion: v1beta3
kind: Service
metadata:
  labels:
    name: grafana
  name: grafana-service
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: povs
    component: grafana
