apiVersion: v1beta3
kind: ReplicationController
metadata:
  labels:
    name: sensu
  name: sensu-server
spec:
  replicas: 2
  selector:
      component: sensu-server
  template:
    metadata:
      labels:
        app: povs
        component: sensu-server
    spec:
      containers:
      - image: arypurnomoz/sensu-server
        name: sensu-server
        resources:
          limits:
            cpu: 100m
